//Rules table
token_t rulesTable [][5]= {
/*  1 : S_TYPE        */ { T_VOID       , T_e          , T_e          , T_e          , T_e          , },
/*  2 : S_TYPE        */ { T_TYPE       , T_e          , T_e          , T_e          , T_e          , },
/*  3 : S_ADD         */ { T_ADD        , T_e          , T_e          , T_e          , T_e          , },
/*  4 : S_ADD         */ { T_MINUS      , T_e          , T_e          , T_e          , T_e          , },
/*  5 : S_START       */ { S_TYPE       , T_VAR        , S_START_A    , T_e          , T_e          , },
/*  6 : S_START       */ { T_e          , T_e          , T_e          , T_e          , T_e          , },
/*  7 : S_START_A     */ { S_BRACK_EXP  , S_IDLIST     , T_SEMI       , S_START      , T_e          , },
/*  8 : S_START_A     */ { T_LPAR       , S_PARM_LIST  , T_RPAR       , S_FUNC_DEF   , S_CODE       , },
/*  9 : S_BRACK_EXP   */ { T_LBRACK     , S_EXP        , T_RBRACK     , T_e          , T_e          , },
/* 10 : S_BRACK_EXP   */ { T_e          , T_e          , T_e          , T_e          , T_e          , },
/* 11 : S_IDLIST      */ { T_COMMA      , T_VAR        , S_BRACK_EXP  , S_IDLIST     , T_e          , },
/* 12 : S_IDLIST      */ { T_e          , T_e          , T_e          , T_e          , T_e          , },
/* 13 : S_PARM_LIST   */ { T_TYPE       , T_VAR        , S_PARM_LIST_A, T_e          , T_e          , },
/* 14 : S_PARM_LIST   */ { T_VOID       , S_PARM_LIST_C, T_e          , T_e          , T_e          , },
/* 15 : S_PARM_LIST   */ { T_e          , T_e          , T_e          , T_e          , T_e          , },
/* 16 : S_PARM_LIST_A */ { T_COMMA      , S_PARM_LIST_B, T_e          , T_e          , T_e          , },
/* 17 : S_PARM_LIST_A */ { T_e          , T_e          , T_e          , T_e          , T_e          , },
/* 18 : S_PARM_LIST_B */ { S_TYPE       , T_VAR        , S_PARM_LIST_A, T_e          , T_e          , },
/* 19 : S_PARM_LIST_C */ { T_VAR        , S_PARM_LIST_A, T_e          , T_e          , T_e          , },
/* 20 : S_PARM_LIST_C */ { T_e          , T_e          , T_e          , T_e          , T_e          , },
/* 21 : S_FUNC_DEF    */ { T_LBRACE     , S_DATA       , S_STATEMENT  , T_RBRACE     , T_e          , },
/* 22 : S_FUNC_DEF    */ { T_SEMI       , T_e          , T_e          , T_e          , T_e          , },
/* 23 : S_DATA        */ { S_TYPE       , T_VAR        , S_IDLIST     , S_DATA       , T_e          , },
/* 24 : S_DATA        */ { T_E          , T_e          , T_e          , T_e          , T_e          , },
/* 25 : S_STATEMENT   */ { T_VAR        , S_STATEMENT_A, S_STATEMENT  , T_e          , T_e          , },
/* 26 : S_STATEMENT_A */ { S_BRACK_EXP  , T_EQ         , S_EXP        , T_SEMI       , S_STATMENT   , },
/* 27 : S_STATENENT_A */ { T_LPAR       , S_EXP_LIST   , T_RPAR       , T_SEMI       , S_STATE      , },
/* 28 : S_STATEMENT   */ { T_E          , T_e          , T_e          , T_e          , T_e          , },
/* 29 : S_CODE        */ { S_FUNC       , S_FUNC_DEC   , S_CODE       , T_e          , T_e          , },
/* 30 : S_CODE        */ { T_e          , T_e          , T_e          , T_e          , T_e          , },
/* 31 : S_EXP         */ { S_TERM       , S_EXP_A      , T_e          , T_e          , T_e          , },
/* 32 : S_EXP_A       */ { S_ADD        , S_TERM       , S_EXP_A      , T_e          , T_e          , },
/* 33 : S_EXP_A       */ { T_e          , T_e          , T_e          , T_e          , T_e          , },
};
