#include <stdio.h>
#define read(x) scanf("%d",&x)
#define write(x) printf("%d\n",x)
#define print(x) printf(x)
int getinput (){

    int local[2];


    local[1] = - 1;
    local[0] = local[1];
    label_0: ;
    if( 0 > local[0]) goto label_2;
    goto label_1;
    label_2: ;
        read ( local[0] );
        if( 0 > local[0])  goto label_3;
        goto label_4;
        label_3: ;
            print ( "I need a non-negative number: " );
        label_4: ;
    goto label_0;
    label_1: ;
    return local[0];
};
int main (){

    int local[43];

    print ( "Welcome to the United States 1040 federal income tax program.\n" );
    print ( "(Note: this isn't the real 1040 form. If you try to submit your\n" );
    print ( "taxes this way, you'll get what you deserve!\n\n" );
    print ( "Answer the following questions to determine what you owe.\n\n" );
    print ( "Total wages, salary, and tips? " );
    local[23] = getinput ( );
    local[0] = local[23];
    print ( "Taxable interest (such as from bank accounts)? " );
    local[24] = getinput ( );
    local[1] = local[24];
    print ( "Unemployment compensation, qualified state tuition, and Alaska\n" );
    print ( "Permanent Fund dividends? " );
    local[25] = getinput ( );
    local[2] = local[25];
    local[27] = local[0] + local[1];
    local[26] = local[27] + local[2];
    local[3] = local[26];
    print ( "Your adjusted gross income is: " );
    write ( local[3] );
    print ( "Enter <1> if your parents or someone else can claim you on their" );
    print ( " return. \nEnter <0> otherwise: " );
    local[28] = getinput ( );
    local[12] = local[28];
    if( 0 != local[12])  goto label_5;
    goto label_6;
    label_5: ;
        local[29] = local[0] + 250;
        local[14] = local[29];
        local[15] = 700;
        local[16] = local[15];
        if( local[16] < local[14])  goto label_7;
        goto label_8;
        label_7: ;
            local[16] = local[14];
        label_8: ;
        print ( "Enter <1> if you are single, <0> if you are married: " );
        local[30] = getinput ( );
        local[13] = local[30];
        if( 0 != local[13])  goto label_9;
        goto label_10;
        label_9: ;
            local[17] = 7350;
        label_10: ;
        if( 0 == local[13])  goto label_11;
        goto label_12;
        label_11: ;
            local[17] = 4400;
        label_12: ;
        local[18] = local[16];
        if( local[18] > local[17])  goto label_13;
        goto label_14;
        label_13: ;
            local[18] = local[17];
        label_14: ;
        local[19] = 0;
        if( local[13] == 0)  goto label_15;
        goto label_16;
        label_15: ;
            print ( "Enter <1> if your spouse can be claimed as a dependant, " );
            print ( "enter <0> if not: " );
            local[31] = getinput ( );
            local[22] = local[31];
            if( 0 == local[22])  goto label_17;
            goto label_18;
            label_17: ;
                local[19] = 2800;
            label_18: ;
        label_16: ;
        local[32] = local[18] + local[19];
        local[20] = local[32];
        local[4] = local[20];
    label_6: ;
    if( 0 == local[12])  goto label_19;
    goto label_20;
    label_19: ;
        print ( "Enter <1> if you are single, <0> if you are married: " );
        local[33] = getinput ( );
        local[13] = local[33];
        if( 0 != local[13])  goto label_21;
        goto label_22;
        label_21: ;
            local[4] = 12950;
        label_22: ;
        if( 0 == local[13])  goto label_23;
        goto label_24;
        label_23: ;
            local[4] = 7200;
        label_24: ;
    label_20: ;
    local[34] = local[3] - local[4];
    local[5] = local[34];
    if( local[5] < 0)  goto label_25;
    goto label_26;
    label_25: ;
        local[5] = 0;
    label_26: ;
    print ( "Your taxable income is: " );
    write ( local[5] );
    print ( "Enter the amount of Federal income tax withheld: " );
    local[35] = getinput ( );
    local[6] = local[35];
    print ( "Enter <1> if you get an earned income credit (EIC); " );
    print ( "enter 0 otherwise: " );
    local[36] = getinput ( );
    local[21] = local[36];
    local[7] = 0;
    if( 0 != local[21])  goto label_27;
    goto label_28;
    label_27: ;
        print ( "OK, I'll give you a thousand dollars for your credit.\n" );
        local[7] = 1000;
    label_28: ;
    local[37] = local[7] + local[6];
    local[8] = local[37];
    print ( "Your total tax payments amount to: " );
    write ( local[8] );
    local[40] = local[5] * 28;
    local[39] = local[40] + 50;
    local[38] = local[39] / 100;
    local[9] = local[38];
    print ( "Your total tax liability is: " );
    write ( local[9] );
    local[41] = local[8] - local[9];
    local[10] = local[41];
    if( local[10] < 0)  goto label_29;
    goto label_30;
    label_29: ;
        local[10] = 0;
    label_30: ;
    if( local[10] > 0)  goto label_31;
    goto label_32;
    label_31: ;
        print ( "Congratulations, you get a tax refund of $" );
        write ( local[10] );
    label_32: ;
    local[42] = local[9] - local[8];
    local[11] = local[42];
    if( local[11] >= 0)  goto label_33;
    goto label_34;
    label_33: ;
        print ( "Bummer. You owe the IRS a check for $" );
        write ( local[11] );
    label_34: ;
    if( local[11] < 0)  goto label_35;
    goto label_36;
    label_35: ;
        local[11] = 0;
    label_36: ;
    print ( "Thank you for using ez-tax.\n" );
};
